// Fixed public error categories shared with the HTTPS backend. No raw remote output.
package main

var publicErrors = map[string]bool{
	"host_memory_reserve_exhausted":    true,
	"invalid_host_settings":            true,
	"invalid_relay":                    true,
	"invalid_owner_attestation":        true,
	"invalid_replay_floor":             true,
	"relay_mesh_not_supported":         true,
	"unsupported_environment":          true,
	"host_command_failed":              true,
	"host_command_failed_or_timed_out": true,
	"host_response_too_large":          true,
	"nostr_helper_failed":              true,
	"nostr_helper_invalid":             true,
	"host_capacity_unavailable":        true,
	"requested_cpu_exceeds_host":       true,
	"requested_memory_exceeds_host":    true,

	"connection_revoked_or_invalid":                         true,
	"configure_relay_first":                                 true,
	"desktop_launch_contract_required":                      true,
	"relay_mismatch":                                        true,
	"owner_attestation_required":                            true,
	"human_key_must_not_be_deployed":                        true,
	"unsupported_harness_use_codex_acp_or_claude_agent_acp": true,
	"unsupported_provider_configuration":                    true,
	"set_bot_parallelism_to_one":                            true,
	"stop_native_bot_before_changing_settings":              true,
	"stop_native_bot_before_image_upgrade":                  true,
	"aggregate_memory_budget_exceeded":                      true,
	"registered_bot_limit":                                  true,
	"image_changed_revalidate_before_deploy":                true,
	"deployment_not_running_inspect_host":                   true,
	"invalid_payload":                                       true,
	"invalid_environment":                                   true,
	"invalid_parallelism":                                   true,
	"custom_harness_arguments_not_supported":                true,
	"invalid_agent_identity":                                true,
	"public_anyone_mode_disabled":                           true,
	"invalid_allowlist":                                     true,
	"allowlist_required":                                    true,
	"invalid_name":                                          true,
	"invalid_memory":                                        true,
	"invalid_cpu":                                           true,
	"invalid_workspace":                                     true,
	"invalid_turn_seconds":                                  true,
	"invalid_turn_limit":                                    true,
	"invalid_window":                                        true,
	"invalid_daily_limit":                                   true,
	"invalid_native_turn_timeout":                           true,
	"invalid_idle_timeout":                                  true,
	"container_name_collision_no_changes_made":              true,
	"service_unavailable_check_docker_manager":              true,
}
